In [1]:
import pandas as pd

In [2]:
# Leitura do Excel
df = pd.read_excel("data/Planilha_Vendas_Teste.xlsx", sheet_name="d_Pedidos")

In [3]:
df

,IdPedido,IdCliente,Cliente,Data,Produto,Valor (R$),Status
0,1001,101,João Silva,2025-01-03,ARROZ BRANCO 5KG,25.0,Concluida
1,1002,102,Maria Souza,2025-01-05,ARROZ BRANCO 2KG,12.0,Em aberto
2,1003,103,Pedro Lima,2025-01-06,ARROZ PARBO 5KG,27.0,Em aberto
3,1004,101,João Silva,2025-01-07,ARROZ INTEGRAL 5KG,30.0,Em aberto
4,1005,104,Lucas Pereira,2025-01-08,ARROZ BRANCO 5KG,26.0,Concluida
5,1006,105,Carla Mendes,2025-01-09,ARROZ PARBO 2KG,13.0,Concluida
6,1007,106,Paulo Rocha,2025-01-10,ARROZ INTEGRAL 2KG,15.0,Concluida
7,1008,102,Maria Souza,2025-01-11,ARROZ BRANCO 2KG,12.5,Concluida
8,1009,107,Marcos Silva,2025-01-12,ARROZ BRANCO 5KG,24.9,Concluida
9,1010,108,Juliana Alves,2025-01-13,ARROZ INTEGRAL 5KG,29.5,Cancelada
10,1011,109,Thiago Nunes,2025-01-14,ARROZ PARBO 2KG,13.2,Concluida
11,1012,110,Fernanda Reis,2025-01-15,ARROZ BRANCO 5KG,25.5,Em aberto
12,1013,111,Eduardo Gomes,2025-01-16,ARROZ INTEGRAL 2KG,15.3,Em aberto
13,1014,112,Patrícia Luz,2025-01-17,ARROZ BRANCO 2KG,11.9,Em aberto
14,1015,113,André Costa,2025-01-18,ARROZ PARBO 5KG,27.5,Concluida
15,1016,114,Carolina Lima,2025-01-19,ARROZ INTEGRAL 2KG,15.0,Concluida
16,1017,115,Guilherme Paz,2025-01-20,ARROZ BRANCO 5KG,26.0,Concluida
17,1018,116,Daniela Lopes,2025-01-21,ARROZ PARBO 5KG,28.0,Em aberto
18,1019,112,Patrícia Luz,2025-01-22,ARROZ BRANCO 2KG,12.0,Concluida
19,1020,108,Juliana Alves,2025-01-23,ARROZ INTEGRAL 5KG,30.0,Concluida
20,1021,117,Adriano Matos,2025-01-24,ARROZ PARBO 2KG,13.5,Concluida
21,1022,118,Marina Borges,2025-01-25,ARROZ BRANCO 5KG,25.0,Concluida
22,1023,108,Juliana Alves,2025-01-26,ARROZ INTEGRAL 2KG,15.0,Concluida
23,1024,119,Camila Ramos,2025-01-27,ARROZ BRANCO 2KG,12.3,Concluida
24,1025,120,Diego Barbosa,2025-01-28,ARROZ PARBO 5KG,27.8,Concluida
25,1026,121,Larissa Melo,2025-01-29,ARROZ INTEGRAL 5KG,29.9,Concluida
26,1027,122,Sérgio Lopes,2025-01-30,ARROZ BRANCO 5KG,25.7,Concluida
27,1028,123,Amanda Costa,2025-01-31,ARROZ INTEGRAL 2KG,14.9,Concluida
28,1029,124,Tatiane Lopes,2025-02-01,ARROZ BRANCO 2KG,12.1,Concluida
29,1030,125,Sofia Martins,2025-02-02,ARROZ PARBO 5KG,28.2,Concluida
30,1031,126,Rodrigo Pires,2025-02-03,ARROZ BRANCO 5KG,26.2,Concluida
31,1032,116,Daniela Lopes,2025-02-04,ARROZ PARBO 2KG,13.0,Cancelada
32,1033,116,Daniela Lopes,2025-02-05,ARROZ INTEGRAL 5KG,30.0,Cancelada
33,1034,127,Aline Moreira,2025-02-06,ARROZ BRANCO 2KG,11.8,Cancelada
34,1035,128,Jorge Andrade,2025-02-07,ARROZ BRANCO 5KG,25.5,Cancelada
35,1036,116,Daniela Lopes,2025-02-08,ARROZ INTEGRAL 2KG,15.4,Concluida
36,1037,116,Daniela Lopes,2025-02-09,ARROZ PARBO 5KG,27.3,Concluida
37,1038,116,Daniela Lopes,2025-02-10,ARROZ BRANCO 2KG,12.4,Concluida
38,1039,129,Henrique Dias,2025-02-11,ARROZ BRANCO 5KG,26.1,Concluida
39,1040,130,Paula Correia,2025-02-12,ARROZ PARBO 2KG,13.1,Concluida
40,1041,131,Fábio Moura,2025-02-13,ARROZ INTEGRAL 5KG,29.7,Concluida
41,1042,132,Leonardo Dias,2025-02-14,ARROZ BRANCO 2KG,12.2,Concluida
42,1043,133,Marcelo Pinto,2025-02-15,ARROZ PARBO 5KG,28.5,Concluida
43,1044,134,Bianca Rocha,2025-02-16,ARROZ BRANCO 5KG,25.3,Concluida
44,1045,132,Leonardo Dias,2025-02-17,ARROZ INTEGRAL 2KG,15.1,Concluida
45,1046,135,Luana Santos,2025-02-18,ARROZ BRANCO 2KG,11.9,Concluida
46,1047,136,Wellington Luz,2025-02-19,ARROZ PARBO 2KG,13.4,Cancelada
47,1048,137,Beatriz Moraes,2025-02-20,ARROZ INTEGRAL 5KG,30.2,Cancelada
48,1049,115,Guilherme Paz,2025-02-19,ARROZ BRANCO 5KG,26.0,Cancelada
49,1050,116,Daniela Lopes,2025-02-20,ARROZ PARBO 5KG,28.0,Concluida

In [4]:
print(df["Status"].value_counts())

Status
Concluida    35
Cancelada     8
Em aberto     7
Name: count, dtype: int64

In [5]:
# Filtrar apenas pedidos com status "Concluida"
concluidos = df[df["Status"] == "Concluida"]

In [6]:
concluidos

,IdPedido,IdCliente,Cliente,Data,Produto,Valor (R$),Status
0,1001,101,João Silva,2025-01-03,ARROZ BRANCO 5KG,25.0,Concluida
4,1005,104,Lucas Pereira,2025-01-08,ARROZ BRANCO 5KG,26.0,Concluida
5,1006,105,Carla Mendes,2025-01-09,ARROZ PARBO 2KG,13.0,Concluida
6,1007,106,Paulo Rocha,2025-01-10,ARROZ INTEGRAL 2KG,15.0,Concluida
7,1008,102,Maria Souza,2025-01-11,ARROZ BRANCO 2KG,12.5,Concluida
8,1009,107,Marcos Silva,2025-01-12,ARROZ BRANCO 5KG,24.9,Concluida
10,1011,109,Thiago Nunes,2025-01-14,ARROZ PARBO 2KG,13.2,Concluida
14,1015,113,André Costa,2025-01-18,ARROZ PARBO 5KG,27.5,Concluida
15,1016,114,Carolina Lima,2025-01-19,ARROZ INTEGRAL 2KG,15.0,Concluida
16,1017,115,Guilherme Paz,2025-01-20,ARROZ BRANCO 5KG,26.0,Concluida
18,1019,112,Patrícia Luz,2025-01-22,ARROZ BRANCO 2KG,12.0,Concluida
19,1020,108,Juliana Alves,2025-01-23,ARROZ INTEGRAL 5KG,30.0,Concluida
20,1021,117,Adriano Matos,2025-01-24,ARROZ PARBO 2KG,13.5,Concluida
21,1022,118,Marina Borges,2025-01-25,ARROZ BRANCO 5KG,25.0,Concluida
22,1023,108,Juliana Alves,2025-01-26,ARROZ INTEGRAL 2KG,15.0,Concluida
23,1024,119,Camila Ramos,2025-01-27,ARROZ BRANCO 2KG,12.3,Concluida
24,1025,120,Diego Barbosa,2025-01-28,ARROZ PARBO 5KG,27.8,Concluida
25,1026,121,Larissa Melo,2025-01-29,ARROZ INTEGRAL 5KG,29.9,Concluida
26,1027,122,Sérgio Lopes,2025-01-30,ARROZ BRANCO 5KG,25.7,Concluida
27,1028,123,Amanda Costa,2025-01-31,ARROZ INTEGRAL 2KG,14.9,Concluida
28,1029,124,Tatiane Lopes,2025-02-01,ARROZ BRANCO 2KG,12.1,Concluida
29,1030,125,Sofia Martins,2025-02-02,ARROZ PARBO 5KG,28.2,Concluida
30,1031,126,Rodrigo Pires,2025-02-03,ARROZ BRANCO 5KG,26.2,Concluida
35,1036,116,Daniela Lopes,2025-02-08,ARROZ INTEGRAL 2KG,15.4,Concluida
36,1037,116,Daniela Lopes,2025-02-09,ARROZ PARBO 5KG,27.3,Concluida
37,1038,116,Daniela Lopes,2025-02-10,ARROZ BRANCO 2KG,12.4,Concluida
38,1039,129,Henrique Dias,2025-02-11,ARROZ BRANCO 5KG,26.1,Concluida
39,1040,130,Paula Correia,2025-02-12,ARROZ PARBO 2KG,13.1,Concluida
40,1041,131,Fábio Moura,2025-02-13,ARROZ INTEGRAL 5KG,29.7,Concluida
41,1042,132,Leonardo Dias,2025-02-14,ARROZ BRANCO 2KG,12.2,Concluida
42,1043,133,Marcelo Pinto,2025-02-15,ARROZ PARBO 5KG,28.5,Concluida
43,1044,134,Bianca Rocha,2025-02-16,ARROZ BRANCO 5KG,25.3,Concluida
44,1045,132,Leonardo Dias,2025-02-17,ARROZ INTEGRAL 2KG,15.1,Concluida
45,1046,135,Luana Santos,2025-02-18,ARROZ BRANCO 2KG,11.9,Concluida
49,1050,116,Daniela Lopes,2025-02-20,ARROZ PARBO 5KG,28.0,Concluida

In [7]:
# Somar a coluna de valor
total_valor = concluidos["Valor (R$)"].sum()

In [8]:
print(f'Total de vendas concluídas: R${total_valor:.2f}')

Total de vendas concluídas: R$715.70